### ISSUE TITLE
필요한 쿼리 목록 정리

### ISSUE THREAD

**Issue by deptno** [deptno/abandoned-animals#2]
필요한 쿼리 목록 및 조건 기술

**Comment by sohee-lee7** [comment]
## 유기동물 쿼리
- 날짜
- 지역 (시/시군구)
- 보호소
- 축종 (개/고양이/기타)
- 품종 (푸들 ..)
- `processState` (종료(입양), 보호중 .. 등) => 이건 공공데이터 쿼리 날릴 때 `state` 값하고 매칭되는 건지 모르겠네요. 실제 데이터에 있는 `procssState` 이 값이 의미 있을 것 같아요.

## 보호소 정보 쿼리
- 지역 (시/시군구)

**Comment by deptno** [comment]
로우 데이터 제공 중, UI 개선에 따른 쿼리 필요 재 정립 이슈 따로 발행
